"""add refresh token jti hash

Revision ID: 87c4fe03f0f4
Revises: eceb8850879d
Create Date: 2026-06-06 01:28:13.853118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c4fe03f0f4'
down_revision: Union[str, Sequence[str], None] = 'eceb8850879d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_jti_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_jti_hash')
    # ### end Alembic commands ###
